/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void genrate_interrupt(void){
	uint32_t *pSTIR  = (uint32_t *) 0xE000EF00;
	uint32_t *pISER0 = (uint32_t *) 0xE000E100;

	// enable IRQ3 interrupt
	*pISER0 |= (1 << 3);

	// genrate Interrupt from software
	*pSTIR = (3 & 0x1FF);
}

void change_access_level_unprev(void ){
	// read
	__asm volatile ("MRS R0, CONTROL");
	// modify
	__asm volatile ("ORR R0, R0,#0x01");
	// write
	__asm volatile ("MSR CONTROL, R0");
}

/* start with thread + priviledge access level */
int main(void)
{
	printf("In thread mode : before interrupt ... \n ");

	change_access_level_unprev();

	genrate_interrupt();

	printf("In thread mode : after interrupt ... \n ");

    return 0;
}

void RTC_WKUP_IRQHandler(void){
	printf("In handler mode : ISR \n");
}

void HardFault_Handler(void){
	printf("Hard fault detected...\n ");
	while(1);
}
